#ifndef BOARD_CONF_H__
#define BOARD_CONF_H__

#define NRF_CRYPTO_BACKEND_CC310_ENABLED 1

#define NRFX_PWM3_ENABLED 1
#define PWM3_ENABLED 1

#define NRFX_QSPI_ENABLED 1
#define QSPI_ENABLED 1

#define NRFX_USBD_ENABLED 1
#define USBD_ENABLED 1

#define APP_USBD_AUDIO_ENABLED 1
#define APP_USBD_ENABLED 1
#define APP_USBD_CDC_ACM_ENABLED 1
#define APP_USBD_HID_ENABLED 1
#define APP_USBD_HID_GENERIC_ENABLED 1
#define APP_USBD_HID_KBD_ENABLED 1
#define APP_USBD_HID_MOUSE_ENABLED 1
#define APP_USBD_MSC_ENABLED 1

#endif /* BOARD_CONF_H__ */